### ISSUE TITLE
Outside dependencies hard-coded in Makefile

### ISSUE THREAD

**Issue by awickert** [KCallaghan/TWSM#1]
Within "Combined/Makefile", there are dependencies on RichDEM that are based on code that is not included in this repository. In order for this to be compiled by an end-user, you will need either a "configure" step or to directly include RichDEM in this repo and link to it here.

**Comment by r-barnes** [comment]
RichDEM and surfacewater are submodules. Acquire them with:
```
git submodule update --init --recursive
```

**Comment by awickert** [comment]
Thanks! But:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Once this is managed, I will fork, add this to the README, and issue a pull request, unless one of you beats me to it.

**Comment by awickert** [comment]
@KCallaghan has now helped me to get this working, via an old version of RichDEM. It looks like the only change was the name of the array object. When I have a chance, I will see if I can get this updated to work with the modern RichDEM -- and hopefully by then, @r-barnes will be able to resolve this permissions issue.

**Comment by r-barnes** [comment]
We should also update the build system to use cmake. That will simplify a number of things (hopefully).

**Comment by r-barnes** [comment]
#8 address this issue somewhat.

**Comment by r-barnes** [comment]
#9 addresses Andy's original problem: submodules should be pulled from HTTPS by default.
