### ISSUE TITLE
Specify number of threads for parallel execution

### ISSUE THREAD

**Issue by awickert** [KCallaghan/TWSM#27]
Currently, it seems that OpenMP is just using all available threads. This might not always be the preferred behavior. Therefore (and I can certainly do this too), I would suggest changing:
`#pragma omp parallel`
to
`#pragma omp parallel num_threads( thread_count )`,
where `thread_count` could be a new parameter defined in the `.cfg` file.

**Comment by r-barnes** [comment]
Another option is to use `export OMP_NUM_THREADS=4` before running the executable. This limits the maximum number of threads OpenMP will use. See: https://www.openmp.org/spec-html/5.0/openmpse50.html

**Comment by awickert** [comment]
Setting the environment variable seems a good way to do this without needing to muck about in the code. Since my PR points to my main branch, I think that I can add this to the README that the same PR will include this -- if so, I'll add a comment there as well.

**Comment by KCallaghan** [comment]
This is resolved in [this commit](9adcb04b0c6be829bd8a32838ed26ed8a7db350e). Users should set the number of threads in their config file with ```parallel_threads```.
