### ISSUE TITLE
Write outputs to a table

### ISSUE THREAD

**Issue by awickert** [KCallaghan/TWSM#29]
Consider writing outputs to a tab- or comma-separated table such that users needn't write their own convoluted string-parsing codes to pull the numbers of of the human-readable text.

**Comment by r-barnes** [comment]
JSON might also be an option, depending on the output.

**Comment by awickert** [comment]
Agreed! Anything that is standardized and can be read by a standard library (instead of home-grown code) will increase interoperability, decrease our time investment, improve usability, and reduce the potential for errors.

**Comment by KCallaghan** [comment]
I have updated the text output to print values in a space-separated table.
