### ISSUE TITLE
Zero-pad output time step numbers

### ISSUE THREAD

**Issue by awickert** [KCallaghan/TWSM#30]
Consider using zero padding up to 1 OOM beyond the highest possible number, and/or just setting it to a big number.

This will allow the files to all be sorted properly with a `glob` operation, thereby making working with outputs much easier.

**Comment by r-barnes** [comment]
Nice idea!

**Comment by KCallaghan** [comment]
Resolved in [this commit](https://github.com/KCallaghan/WTM/commit/230ace9ac56e6c5c969c9236066c3efef0af0707).
