### ISSUE TITLE
Mass-conservation check?

### ISSUE THREAD

**Issue by awickert** [KCallaghan/TWSM#37]
Does anywhere in the code record the total amount of water lost to the oceans? If it does, then we could check:

```
mass_in_domain_now =? mass_in_domain_before + mass_added - mass_lost_to_oceans
```

And this could tell us whether addressing mass balance (#36) may be important or not -- and whether it helps or not.

**Comment by KCallaghan** [comment]
This issue has been addressed in [this commit](https://github.com/KCallaghan/WTM/commit/e2ba68ee536c814da12902d163d19da1f6904800).
